services:
  pgsql:
    image: postgres:15
    container_name: eth-indexer-pgsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: pelith
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  indexer:
    build:
      context: .
      dockerfile: ./docker/indexer.Dockerfile
    container_name: eth-indexer-indexer
    depends_on:
      pgsql:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@pgsql:5432/pelith?sslmode=disable

  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: eth-indexer-api
    depends_on:
      pgsql:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@pgsql:5432/pelith?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  pgdata: